repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
      args:
        - --in-place
        - --remove-all-unused-imports
        - --expand-star-imports
        - --remove-duplicate-keys
        - --remove-unused-variables
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.1.1
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==21.7b0]
   - id: nbqa-pyupgrade
     additional_dependencies: [pyupgrade==2.7.3]
   - id: nbqa-isort
     additional_dependencies: [isort==5.6.4]
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: []
      require_serial: true
      additional_dependencies:
        ["platformdirs==2.2.0", "types-pkg_resources==0.1.3", "types-toml==0.1.3"]
      exclude: tests/functional/|tests/input|tests(/.*)*/data|tests/regrtest_data/|tests/data/|tests(/.*)+/conftest.py|doc/|bin/