default_stages: [push]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
  -   repo: https://github.com/pycqa/pylint
      rev: v2.10.2
      hooks:
      -   id: pylint
          args:
          - --max-line-length=120
          - --ignore-imports=yes
          - -d duplicate-code
          - --disable=I,E,R,W,C,F
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: no-commit-to-branch
          args: ['--branch', 'master', '--branch', 'staging']