name: Push a Python package to Azure Artifacts
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Testing pre-build code with pytest
      run: |
        pytest lib_template/
    - name: Install library
      run: |
        python setup.py install
    - name: Test after installing library
      run: |
        pytest .
    - name: Generate binary distribution
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Generate binary distribution
      run: |
        python -m twine upload -r <organizationName> dist/*
        python -m twine upload -r feedName --config-file $(PYPIRC_PATH) dist/*.whl