# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('setup.py') }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        autoflake --in-place -r --ignore-init-module-imports --remove-unused-variables --remove-all-unused-imports lib_template/
        flake8 lib_template --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 lib_template --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
    - name: Testing pre-build code with pytest
      run: |
        pytest lib_template/
    - name: Install library
      run: |
        python setup.py install
    - name: Test after installing library
      run: |
        pytest .
    - name: Generate binary distribution
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
      
